apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
      app: load-balancer
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: load-balancer
  type: NodePort


